function fig = nova_figura(largura_pol, altura_pol, nome)
%NOVA_FIGURA Cria uma figura com tamanho (polegadas) e fonte serifada do artigo.
fig = figure('Color', 'w', 'Units', 'inches', 'Name', nome, 'NumberTitle', 'off');
fig.Position = [1 1 largura_pol altura_pol];
fig.PaperUnits = 'inches';
fig.PaperSize = [largura_pol altura_pol];
fig.PaperPosition = [0 0 largura_pol altura_pol];
set(fig, 'DefaultAxesFontName', 'Times New Roman', ...
         'DefaultAxesFontSize', 10, ...
         'DefaultAxesLineWidth', 0.6, ...
         'DefaultAxesBox', 'on', ...
         'DefaultAxesXGrid', 'on', 'DefaultAxesYGrid', 'on', ...
         'DefaultAxesGridAlpha', 0.25, ...
         'DefaultAxesTitleFontWeight', 'normal', ...
         'DefaultAxesLabelFontSizeMultiplier', 1.125, ...
         'DefaultAxesTitleFontSizeMultiplier', 1.125, ...
         'DefaultTextFontName', 'Times New Roman', ...
         'DefaultTextFontSize', 10, ...
         'DefaultLegendFontName', 'Times New Roman', ...
         'DefaultLegendFontSize', 9.5, ...
         'DefaultLegendBox', 'off');
end
